spring:
  application:
    name: todo-app

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: sandbox_user
    password: sandbox_password
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true